import XCTest
@testable import Pits

final class JSONLDecoderTests: XCTestCase {
    private func decode(_ line: String) -> JSONLEntry? {
        JSONLDecoder.decode(line: line)
    }

    func test_humanTurn_plainText() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":[{"type":"text","text":"hi"}]}}"#
        guard case .human(let h) = decode(line) else { return XCTFail("expected human") }
        XCTAssertEqual(h.sessionId, "s")
        XCTAssertEqual(h.text, "hi")
    }

    func test_humanTurn_stringContent() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":"hi"}}"#
        guard case .human(let h) = decode(line) else { return XCTFail("expected human") }
        XCTAssertEqual(h.text, "hi")
    }

    /// Claude Code wraps slash-command invocations in a synthetic user entry
    /// prefaced with a caveat wrapper — it's an instruction to the model, not
    /// a human message, so the preview should skip it and let the caller walk
    /// to the next turn (typically the `<command-name>…</command-name>` one).
    func test_humanTurnPreview_skipsLocalCommandCaveat() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":[{"type":"text","text":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"}]}}"#
        guard case .human(let h) = decode(line) else { return XCTFail("expected human") }
        XCTAssertNil(h.text)
    }

    /// Slash-command opener: Claude Code packs the invocation into
    /// <command-name>/foo</command-name>. The preview should surface just
    /// the command slug so the row title reads "/foo".
    func test_humanTurnPreview_extractsSlashCommand() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":[{"type":"text","text":"<command-name>/context</command-name>\n<command-message>context</command-message>\n<command-args></command-args>"}]}}"#
        guard case .human(let h) = decode(line) else { return XCTFail("expected human") }
        XCTAssertEqual(h.text, "/context")
    }

    /// The IDE prepends an <ide_opened_file>…</ide_opened_file> context block
    /// to the first user message. The preview should strip it and return
    /// just the human-authored text.
    func test_humanTurnPreview_stripsIdeOpenedFileTag() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":[{"type":"text","text":"<ide_opened_file>/foo/bar.md</ide_opened_file>"},{"type":"text","text":"So 26k right out of the gate?"}]}}"#
        guard case .human(let h) = decode(line) else { return XCTFail("expected human") }
        XCTAssertEqual(h.text, "So 26k right out of the gate?")
    }

    func test_userToolResultOnly_isNil() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":[{"type":"tool_result","tool_use_id":"x"}]}}"#
        XCTAssertNil(decode(line))
    }

    func test_compactSummary_isNil() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","isCompactSummary":true,"message":{"content":[{"type":"text","text":"hi"}]}}"#
        XCTAssertNil(decode(line))
    }

    func test_assistantTurn_extractsUsage() {
        let line = #"{"type":"assistant","sessionId":"s","requestId":"req_1","timestamp":"2026-04-21T10:00:01.000Z","message":{"model":"claude-opus-4-6-20251001","stop_reason":"end_turn","usage":{"input_tokens":10,"cache_creation_input_tokens":100,"cache_read_input_tokens":900,"output_tokens":50}}}"#
        guard case .turn(let t) = decode(line) else { return XCTFail("expected turn") }
        XCTAssertEqual(t.requestId, "req_1")
        XCTAssertEqual(t.sessionId, "s")
        XCTAssertEqual(t.model, "claude-opus-4-6")
        XCTAssertEqual(t.inputTokens, 10)
        XCTAssertEqual(t.cacheCreationTokens, 100)
        XCTAssertEqual(t.cacheReadTokens, 900)
        XCTAssertEqual(t.outputTokens, 50)
        XCTAssertEqual(t.stopReason, "end_turn")
        XCTAssertFalse(t.isSubagent)
    }

    func test_assistantTurn_syntheticModelIsNil() {
        let line = #"{"type":"assistant","sessionId":"s","requestId":"req_1","timestamp":"2026-04-21T10:00:01.000Z","message":{"model":"<synthetic>","usage":{"input_tokens":1,"cache_creation_input_tokens":0,"cache_read_input_tokens":0,"output_tokens":1}}}"#
        XCTAssertNil(decode(line))
    }

    func test_assistantTurn_subagent() {
        let line = #"{"type":"assistant","sessionId":"s","agentId":"a1","requestId":"req_1","timestamp":"2026-04-21T10:00:01.000Z","message":{"model":"claude-sonnet-4-6","usage":{"input_tokens":1,"cache_creation_input_tokens":0,"cache_read_input_tokens":0,"output_tokens":1}}}"#
        guard case .turn(let t) = decode(line) else { return XCTFail("expected turn") }
        XCTAssertTrue(t.isSubagent)
    }

    func test_otherTypes_areNil() {
        XCTAssertNil(decode(#"{"type":"queue-operation","timestamp":"2026-04-21T10:00:00.000Z"}"#))
        XCTAssertNil(decode(#"{"type":"system","subtype":"compact_boundary","timestamp":"2026-04-21T10:00:00.000Z"}"#))
    }

    func test_aiTitle_decodes() {
        let line = #"{"type":"ai-title","sessionId":"s1","aiTitle":"Batch main thread redraws to fix UI beach-ball"}"#
        guard case .title(let t) = decode(line) else { return XCTFail("expected title") }
        XCTAssertEqual(t.sessionId, "s1")
        XCTAssertEqual(t.title, "Batch main thread redraws to fix UI beach-ball")
    }

    func test_aiTitle_missingFields_isNil() {
        XCTAssertNil(decode(#"{"type":"ai-title","sessionId":"s1"}"#))
        XCTAssertNil(decode(#"{"type":"ai-title","aiTitle":"hi"}"#))
        XCTAssertNil(decode(#"{"type":"ai-title","sessionId":"","aiTitle":"hi"}"#))
    }

    func test_malformedJson_isNil() {
        XCTAssertNil(decode("not json"))
        XCTAssertNil(decode(""))
    }

    /// Real Claude Code JSONL splits cache_creation into 5m/1h. We must honour
    /// that split so the per-tier price (1.25× vs 2× base) is applied correctly.
    func test_assistantTurn_splitsCacheCreationByTier() {
        let line = #"{"type":"assistant","sessionId":"s","requestId":"r","timestamp":"2026-04-21T10:00:00.000Z","message":{"model":"claude-opus-4-7","usage":{"input_tokens":3,"cache_creation_input_tokens":4951,"cache_read_input_tokens":166357,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":4951},"output_tokens":6}}}"#
        guard case .turn(let t) = decode(line) else { return XCTFail("expected turn") }
        XCTAssertEqual(t.cacheCreation5mTokens, 0)
        XCTAssertEqual(t.cacheCreation1hTokens, 4951)
        XCTAssertEqual(t.cacheCreationTokens, 4951, "sum view stays correct")
    }

    /// Older entries (or fixtures) with only the flat `cache_creation_input_tokens`
    /// field — no nested object — fall back to the 5m bucket (the API default).
    func test_assistantTurn_flatCacheCreation_fallsBackTo5m() {
        let line = #"{"type":"assistant","sessionId":"s","requestId":"r","timestamp":"2026-04-21T10:00:00.000Z","message":{"model":"claude-opus-4-6","usage":{"input_tokens":1,"cache_creation_input_tokens":1234,"cache_read_input_tokens":0,"output_tokens":1}}}"#
        guard case .turn(let t) = decode(line) else { return XCTFail("expected turn") }
        XCTAssertEqual(t.cacheCreation5mTokens, 1234)
        XCTAssertEqual(t.cacheCreation1hTokens, 0)
    }

    func test_humanTurn_mixedTextAndToolResult_isHuman() {
        // Defensive pin: an array with both text and tool_result blocks counts as
        // a human turn, matching the Python reference. If this behavior ever
        // needs to change, update this test AND extract.py together.
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":[{"type":"tool_result","tool_use_id":"x"},{"type":"text","text":"and also..."}]}}"#
        guard case .human = decode(line) else { return XCTFail("expected human") }
    }

    /// ISO-8601 without fractional seconds is a valid format Claude Code may
    /// some day produce; the parser falls back so we don't silently drop
    /// entire turns (and their costs).
    func test_timestamp_withoutFractionalSeconds_decodes() {
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00Z","message":{"content":"hi"}}"#
        guard case .human(let h) = decode(line) else { return XCTFail("expected human") }
        XCTAssertEqual(h.sessionId, "s")
    }

    /// humanTurnPreview caps output at 200 chars so the on-disk cache doesn't
    /// store unbounded prompt content (privacy/footprint concern).
    func test_humanTurnPreview_capsAt200Chars() {
        let big = String(repeating: "x", count: 1000)
        let line = #"{"type":"user","sessionId":"s","timestamp":"2026-04-21T10:00:00.000Z","message":{"content":[{"type":"text","text":"\#(big)"}]}}"#
        guard case .human(let h) = decode(line) else { return XCTFail("expected human") }
        XCTAssertEqual(h.text?.count, 200)
    }
}
